services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: sh -c "python -u src/scrape.py"
    env_file:
      - .env
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379
      - FLARESOLVERR_URL=http://flaresolverr:8191
    volumes:
      - .:/app
    depends_on:
      - valkey
      - flaresolverr

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    environment:
      - LOG_LEVEL=debug
      - LOG_HTML=true

  valkey:
    image: valkey/valkey:7.2.5-alpine
    volumes:
      - valkey-data:/data

volumes:
  valkey-data:
